name: Flatpak Build

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target architecture'
        required: true
        type: choice
        options:
          - x86_64
      runner_labels:
        description: 'Runner label (single string), e.g. "ubuntu-latest"'
        required: true
        type: string
        default: ubuntu-latest

jobs:
  flatpak:
    # hosted on GitHub Actions runner
    runs-on: ${{ github.event.inputs.runner_labels }}

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Ladybird.flatpak
          manifest-path: Meta/CMake/flatpak/org.ladybird.Ladybird.json
          arch: ${{ github.event.inputs.arch }}
